### ISSUE TITLE
"docker-compose"ing the descartes-env corrupts WSL2

### ISSUE THREAD

**Issue by sjyi** [cartesi/descartes-tutorials#14] opened 2021-05-27 05:23 UTC
I have windows 10 build 19042.985.
Installed docker desktop.  Finished docker tutorials without any problems.
Followed up to downloading the descartes SDK env.
When docker-compose finishes the WSL2 terminal disappears.
When I reopen a terminal, docker is no longer found.
docker desktop no longer sees the images.
Shutting down WSL with "wsl.exe --shutdown" and restarting does not help.

Reset the WSL, remove any trace of docker in Ubuntu as well as windows.
Repeat the above process.
Again, the same result.

When I reboot the Windows,  I can restart the docker.

When I start descartes-env 
the following containers are running:
alice_logger_1
alice_machine_manager
hardhatnet_1
bob_logger_1
bob_machine_manager_1

the following containers are not running:
alice_dispatcher_1
bob_dispatcher_1
bob_ipfs_1
alice_ipfs_1

I get the following error when I start the descartes-env
================================
Cannot start Docker Compose application. Reason: Error invoking remote method 'compose-action': Error: Command failed: wsl -d Ubuntu -e sh -c "cd \"/home/sj/descartes-tutorials/descartes-env\" && docker-compose --project-name \"descartes-env\" --project-directory \"/home/sj/descartes-tutorials/descartes-env\" up -d" Starting descartes-env_alice_ipfs_1 ... Starting descartes-env_bob_logger_1 ... Starting descartes-env_alice_dispatcher_1 ... Starting descartes-env_bob_dispatcher_1 ... Starting descartes-env_hardhatnet_1 ... Starting descartes-env_bob_ipfs_1 ... Starting descartes-env_alice_logger_1 ... Starting descartes-env_bob_machine_manager_1 ... Starting descartes-env_alice_machine_manager_1 ... Host is already in use by another container Starting descartes-env_alice_ipfs_1 ... error ERROR: for descartes-env_alice_ipfs_1 Cannot start service alice_ipfs: driver failed programming external connectivity on endpoint descartes-env_alice_ipfs_1 (239bc68c615af10f169d0d2cd9c1173fbece42ab5290ef1df55133b0695744e9): Bind for 0.0.0.0:50051 failed: port is already allocated Host is already in use by another container Starting descartes-env_alice_dispatcher_1 ... error ERROR: for descartes-env_alice_dispatcher_1 Cannot start service alice_dispatcher: driver failed programming external connectivity on endpoint descartes-env_alice_dispatcher_1 (61b76ca57f5003db9fb69843d896c973b66036d9a401ca4c5dd40b3a4caaf2bd): Bind for 0.0.0.0:3001 failed: port is already allocated Starting descartes-env_bob_logger_1 ... done Host is already in use by another container Starting descartes-env_bob_dispatcher_1 ... error ERROR: for descartes-env_bob_dispatcher_1 Cannot start service bob_dispatcher: driver failed programming external connectivity on endpoint descartes-env_bob_dispatcher_1 (7d2047ffc68f00317ff23298c899a4b2d1769fb81166fe44ba09602cc4af4e6b): Bind for 0.0.0.0:3002 failed: port is already allocated Host is already in use by another container Starting descartes-env_bob_ipfs_1 ... error ERROR: for descartes-env_bob_ipfs_1 Cannot start service bob_ipfs: driver failed programming external connectivity on endpoint descartes-env_bob_ipfs_1 (b0c2e620693e518637771a6acb4e1191a98b266d97b017592307f5c42928033b): Bind for 0.0.0.0:50052 failed: port is already allocated Starting descartes-env_hardhatnet_1 ... done Starting descartes-env_bob_machine_manager_1 ... done Starting descartes-env_alice_machine_manager_1 ... done Starting descartes-env_alice_logger_1 ... done ERROR: for alice_ipfs Cannot start service alice_ipfs: driver failed programming external connectivity on endpoint descartes-env_alice_ipfs_1 (239bc68c615af10f169d0d2cd9c1173fbece42ab5290ef1df55133b0695744e9): Bind for 0.0.0.0:50051 failed: port is already allocated ERROR: for alice_dispatcher Cannot start service alice_dispatcher: driver failed programming external connectivity on endpoint descartes-env_alice_dispatcher_1 (61b76ca57f5003db9fb69843d896c973b66036d9a401ca4c5dd40b3a4caaf2bd): Bind for 0.0.0.0:3001 failed: port is already allocated ERROR: for bob_dispatcher Cannot start service bob_dispatcher: driver failed programming external connectivity on endpoint descartes-env_bob_dispatcher_1 (7d2047ffc68f00317ff23298c899a4b2d1769fb81166fe44ba09602cc4af4e6b): Bind for 0.0.0.0:3002 failed: port is already allocated ERROR: for bob_ipfs Cannot start service bob_ipfs: driver failed programming external connectivity on endpoint descartes-env_bob_ipfs_1 (b0c2e620693e518637771a6acb4e1191a98b266d97b017592307f5c42928033b): Bind for 0.0.0.0:50052 failed: port is already allocated Encountered errors while bringing up the project.

**Comment by miltonjonat** [comment] 2021-05-27 17:56
Hello @sjyi . I am also running under WSL2 on Windows 10 build 19042.985. I wasn't able to reproduce your issue, which seems to be more related to how to manage Docker containers than something specific to our docker-compose configuration.

The error you displayed above states clearly that "Host is already in use by another container" and that "Bind for 0.0.0.0:XXXXX failed: port is already allocated". I confess I always run this from within WSL's Ubuntu. I couldn't reproduce your situation closing the terminal, interrupting execution with CTRL+C, or even shutting down and restarting wsl altogether. Usually when I rerun `docker-compose up` it simply attaches to whatever services are already running and works.

That being said, the recommended way of shutting down a docker-compose is to run `docker-compose down -v`, as described in the [tutorials README](https://github.com/cartesi/descartes-tutorials#environment). Maybe it would indeed be a good idea to add that to the documentation at https://cartesi.io/en/docs/tutorials/descartes-env/#download-and-run. Do you think that would help? In any case, you should never need to shutdown wsl or restart Docker.
`

**Comment by sjyi** [comment] 2021-05-28 06:03
Thank you @miltonjonat for your explanation.
I had to use Docker Desktop because I could not get docker daemon to run on WSL2. 
I gave it another iteration with a clean WSL2 by turning off the windows feature "Windows Subsystem for Linux" and then back on with restarts.

I then went through the tutorial step by step. https://cartesi.io/en/docs/tutorials/introduction/

I still can't start the docker daemon.
When I tried manually with "systemctl start docker" 
I get "System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down"

I searched how to start docker on WSL, I can't find a solution that doesn't use Docker Desktop.

This may be outside the scope of this project, but would you kindly share how you were able to run docker within WSL's Ubuntu?

Thank you

**Comment by sjyi** [comment] 2021-05-28 16:02
I was able to complete the compilation by setting up the environment with Docker Desktop.  I'll update the details soon.

**Closed** 2021-05-30 03:15 UTC
